server:
  port: 8080

  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

    #servlet:
    #context-path: /api/v0

spring:
  application:
    name: springbootintro

  datasource:
    url: jdbc:postgresql://localhost:5432/sbootintro_db
    username: db_user
    password: db_password
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: name
      password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true

logging: #loggers
  file:
    name: logs/studentapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n" #it shows form of the log messages
  level:
    '[org.springframework.web': WARN
    '[org.hibernate]': INFO
    '[com.tpe]': INFO

management: #actuator
  endpoints:
    web:
      exposure:
        include: ['health', 'loggers', 'env', 'beans'] #there are also some other endpoints like info, threaddump, trace

  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always

    shutdown:
      enabled: true

